site_name: インフラおじさんの日常業務
theme:
  name: material
plugins:
  - search
# タグも使う場合は tags を追加
#  - tags
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Tags: tags.md
  - 自己紹介: hello-world.md
  - エディタの話: about_code_edit.md
  - ZabbixでAIOSを始めよう: AIOPS_Entry_with_Zabbix.md
  - Dockerで新旧バージョンのZabbixをサクッと動かそう: zabbix_docker_5and7.md

# タグ一覧を使う場合は tags.md を1枚用意して nav へ
#  - Tags: tags.md

